[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
ffi = true
verbosity = 5
remappings = [
    '@chainlink/contracts/=lib/chainlink-evm/contracts/',
    'chainlink-evm/=lib/chainlink-evm/',
    'ds-test/=lib/forge-std/lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/',
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config